enum TokenType {
  SPACE = 'SPACE',
  LINE_BREAK = 'LINE_BREAK',
  SEMICOLON = 'SEMICOLON',
  COMMA = 'COMMA',
  PERIOD = 'PERIOD',
  PUNCTUATION = 'PUNCTUATION',
  OPEN_BRACKET = 'OPEN_BRACKET',
  CLOSE_BRACKET = 'CLOSE_BRACKET',
  OPEN_BRACES = 'OPEN_BRACES',
  CLOSE_BRACES = 'BRACES',
  OPEN_PARENTHESIS = 'OPEN_PARENTHESIS',
  CLOSE_PARENTHESIS = 'CLOSE_PARENTHESIS',
  EQUALS = 'EQUALS',
  OPERATOR = 'OPERATOR',
  AT_SYMBOL = 'AT_SYMBOL',
  SYMBOL = 'SYMBOL',
  DOUBLE_QUOTED_STRING = 'DOUBLE_QUOTED_STRING',
  SINGLE_QUOTED_STRING = 'SINGLE_QUOTED_STRING',
  NAME = 'NAME',
  NUMBER = 'NUMBER',
  COMMENT = 'COMMENT',
  ASSIGNMENT = 'ASSIGNMENT',
  OPTION_VALUE_SEPARATOR = 'OPTION_VALUE_SEPARATOR',
  RANGE = 'RANGE',
}

export default interface IToken {
  type: TokenType;
  value: string;
}

export { TokenType };
